# Build settings
safe: true
source: .
destination: ./_site
lsi: false
#pygments: true
highlighter: pygments
# markdown: maruku
markdown: redcarpet
# markdown: rdiscount
# markdown: kramdown


# Site settings
name: CodeArT
title: CodeArT
subtitle: Simplicidade e qualidade

# Contact
email: support@codeart.io
address:
phone:

# Images
logo:
bg:
favicon: http://s3-us-west-2.amazonaws.com/codeart/favicon.png

# Urls
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codeart.io" # the base hostname & protocol for your site
doc_url:
system_url: http://accounts.codeart.io
demo_url:

# Social settings
social:
  - title: facebook
    url: https://www.facebook.com/pages/Codeart/871125929585492
  - title: twitter
    url:
  - title: google-plus
    url:
  - title: apple
    url:
  - title: android
    url:
  - title: linkedin
    url:
  - title: youtube
    url:
  - title: skype
    url:
  - title: github
    url:
  - title: stack-overflow
    url:

google_analytics: UA-58652938-1
twitter_username: paulocheque
github_username:  paulocheque
fb-like: true
fb-share: true
twitter-follow: true
google-like: true


# Sections
sections:
- name:
  slug: #test
  html:

features:
- name:
  url:

services:
- name: Single Sign On
  url: accounts.codeart.io
- name: Tasks
  url: tasks.codeart.io
- name: Safe passwords
  url: safe.codeart.io

plans:
- name:
  price_real:
  price_dollar:
  features:

partner_cols: 3
partners:
- name: IME/USP
  url: https://www.ime.usp.br/dcc/empresas-egressos
  logo: http://ccsl.ime.usp.br/sites/ccsl.ime.usp.br/themes/ccsl/img/ime.png
- name: CCSL/USP
  url: http://ccsl.ime.usp.br
  logo: http://ccsl.ime.usp.br/files/logo_ccsl_preview_small.png
# - name: Neurobox
#   url: http://www.neurobox.com.br
#   logo: http://www.neurobox.com.br/wp-content/uploads/2014/09/logotype-duo.png

portifolio:
- name: Game Algorithms Tournament
  url: http://gatournament.com

team:
- name: Paulo Cheque
  position: CEO
  linkedin:
  github:
  stackoverflow:
  pic: 1


# About
description: >
  CodeArT (codeart.io) is a brazilian company of software development
  and consultant services.

problem: It is easy to complicate simple things.
motivation:
solution: Simplicity with quality and focus.
what:
who:
how:
why:

# Bureaucracy settings
copyright: 2015
contracts:
- name: About
  html:
- name: Terms
  html:
- name: Privacy Policy
  html:
